# Generated by Django 3.1.3 on 2021-02-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elector', '0008_auto_20210106_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
