# Generated by Django 3.1.3 on 2021-02-21 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elector', '0009_auto_20210221_1127'),
        ('canditate', '0008_auto_20201226_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Election', 'verbose_name_plural': 'Elections'},
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_description',
            field=models.TextField(blank=True, null=True, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_title',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Election'),
        ),
        migrations.CreateModel(
            name='ElectorsVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canditate.candidate')),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canditate.vote')),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elector.elector')),
            ],
        ),
    ]
